"""
Designation of hostel staff at IIT Roorkee
"""

#Global Council
DOSW = "dosw"
GSHA = "gsha"

GLOBAL_COUNCIL = (
    (DOSW, "DEAN of students welfare"),
    (GSHA, "GENSEC Hostel Afairs"),
)


# Administrative council
ASSISTANT_WARDEN = "aw"
CHIEF_WARDEN = "cw"
SUPERVISOR = "sup"
WARDEN = "war"
WARDEN_WELLNESS = "waw"

ADMINISTRATIVE_COUNCIL = (
    (ASSISTANT_WARDEN, "Assistant warden"),
    (CHIEF_WARDEN, "Chief warden"),
    (SUPERVISOR, "Supervisor"),
    (WARDEN, "Warden"),
    (WARDEN_WELLNESS, "Warden wellness"),
)

# Student council
BHAWAN_SECRETARY = "bscy"
CULTURAL_SECRETARY = "cscy"
MAINTENANCE_SECRETARY = "mscy"
MESS_SECRETARY = "mescy"
SPORTS_SECRETARY = "sscy"
TECHNICAL_SECRETARY = "tscy"
STUDENT_COUNCIL = (
    (BHAWAN_SECRETARY, "Bhawan secretary"),
    (CULTURAL_SECRETARY, "Cultural secretary"),
    (MAINTENANCE_SECRETARY, "Maintenance secretary"),
    (MESS_SECRETARY, "Mess secretary"),
    (SPORTS_SECRETARY, "Sports secretary"),
    (TECHNICAL_SECRETARY, "Technical secretary"),
)

DESIGNATIONS = ADMINISTRATIVE_COUNCIL + STUDENT_COUNCIL + GLOBAL_COUNCIL

STUDENT_COUNCIL_MAP    = {
    'BHAWAN_SECRETARY': BHAWAN_SECRETARY,
    'CULTURAL_SECRETARY': CULTURAL_SECRETARY,
    'MAINTENANCE_SECRETARY': MAINTENANCE_SECRETARY,
    'MESS_SECRETARY': MESS_SECRETARY,
    'SPORTS_SECRETARY': SPORTS_SECRETARY,
    'TECHNICAL_SECRETARY': TECHNICAL_SECRETARY,
}

ADMINISTRATIVE_COUNCIL_MAP = {
    'ASSISTANT_WARDEN': ASSISTANT_WARDEN,
    'CHIEF_WARDEN': CHIEF_WARDEN,
    'SUPERVISOR': SUPERVISOR,
    'WARDEN': WARDEN,
    'WARDEN_WELLNESS': WARDEN_WELLNESS,
}

GLOBAL_COUNCIL_MAP = {
    'GENSEC HOSTEL AFFAIRS': GSHA,
    'DEAN of students welfare:': DOSW,
}

GLOBAL_COUNCIL_LIST = [
    GSHA,
    DOSW
]

ADMINISTRATIVE_COUNCIL_LIST = [
    ASSISTANT_WARDEN, 
    CHIEF_WARDEN, 
    SUPERVISOR, 
    WARDEN, 
    WARDEN_WELLNESS, 
]

STUDENT_COUNCIL_LIST = [
    BHAWAN_SECRETARY,
    CULTURAL_SECRETARY,
    MAINTENANCE_SECRETARY,
    MESS_SECRETARY,
    SPORTS_SECRETARY,
    TECHNICAL_SECRETARY,
]
