# Generated by Django 3.0.3 on 2020-12-26 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_PERSON_MODEL),
        ('bhawan_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='father',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents_father', to=settings.KERNEL_PERSON_MODEL),
        ),
        migrations.AddField(
            model_name='resident',
            name='fathers_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='having_computer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='mother',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents_mother', to=settings.KERNEL_PERSON_MODEL),
        ),
        migrations.AddField(
            model_name='resident',
            name='mothers_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_PERSON_MODEL),
        ),
    ]
