# Generated by Django 2.2.3 on 2020-11-08 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_PERSON_MODEL),
        ),
    ]
