# Generated by Django 2.2.3 on 2020-02-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bhawan_app", "0002_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("mon", "Monday"),
                            ("tue", "Tuesday"),
                            ("wed", "Wednesday"),
                            ("thu", "Thursday"),
                            ("fri", "Friday"),
                            ("sat", "Saturday"),
                            ("sun", "Sunday"),
                            ("dai", "Daily"),
                        ],
                        max_length=50,
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.TimeField(blank=True, null=True)),
                ("description", models.CharField(max_length=63, blank=True, null=True)),
            ],
            options={"abstract": False,},
        ),
    ]
