# Generated by Django 3.0.3 on 2021-01-05 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_PERSON_MODEL),
        ('bhawan_app', '0002_auto_20201227_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='having_computer',
        ),
        migrations.AlterField(
            model_name='resident',
            name='father',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents_father', to=settings.KERNEL_PERSON_MODEL),
        ),
        migrations.AlterField(
            model_name='resident',
            name='mother',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents_mother', to=settings.KERNEL_PERSON_MODEL),
        ),
    ]
