# Generated by Django 3.0.3 on 2021-03-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0003_auto_20210106_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_resident',
            field=models.BooleanField(default=True),
        ),
    ]
