# Generated by Django 3.2.8 on 2022-02-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0003_auto_20220203_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
