# Generated by Django 3.0.3 on 2021-07-22 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_RESIDENCE_MODEL),
        ('bhawan_app', '0004_resident_is_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('ele', 'Electric'), ('toi', 'Washroom'), ('car', 'Carpentry'), ('cle', 'Cleaning'), ('mes', 'Mess'), ('fdb', 'feedback'), ('oth', 'Others')], default='oth', max_length=10),
        ),
        migrations.AlterField(
            model_name='complainttimeslot',
            name='complaint_type',
            field=models.CharField(choices=[('ele', 'Electric'), ('toi', 'Washroom'), ('car', 'Carpentry'), ('cle', 'Cleaning'), ('mes', 'Mess'), ('fdb', 'feedback'), ('oth', 'Others')], default='oth', max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='designation',
            field=models.CharField(choices=[('aw', 'Assistant warden'), ('cw', 'Chief warden'), ('sup', 'Supervisor'), ('war', 'Warden'), ('waw', 'Warden wellness'), ('bscy', 'Bhawan secretary'), ('cscy', 'Cultural secretary'), ('mscy', 'Maintenance secretary'), ('mescy', 'Mess secretary'), ('sscy', 'Sports secretary'), ('tscy', 'Technical secretary'), ('dosw', 'DEAN of students welfare'), ('gsha', 'GENSEC Hostel Afairs')], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='hosteladmin',
            name='designation',
            field=models.CharField(choices=[('aw', 'Assistant warden'), ('cw', 'Chief warden'), ('sup', 'Supervisor'), ('war', 'Warden'), ('waw', 'Warden wellness'), ('bscy', 'Bhawan secretary'), ('cscy', 'Cultural secretary'), ('mscy', 'Maintenance secretary'), ('mescy', 'Mess secretary'), ('sscy', 'Sports secretary'), ('tscy', 'Technical secretary'), ('dosw', 'DEAN of students welfare'), ('gsha', 'GENSEC Hostel Afairs')], max_length=5),
        ),
        migrations.AlterField(
            model_name='hosteladmin',
            name='hostel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_RESIDENCE_MODEL),
        ),
    ]
