# Generated by Django 3.2.8 on 2022-02-03 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_PERSON_MODEL),
        ('bhawan_app', '0004_alter_resident_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents_father', to=settings.KERNEL_PERSON_MODEL),
        ),
        migrations.AlterField(
            model_name='resident',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residents_mother', to=settings.KERNEL_PERSON_MODEL),
        ),
    ]
