# Generated by Django 2.2.3 on 2020-01-30 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0004_hostelcomplaint_hostelroombooking_hostelvisitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelcomplaint',
            old_name='filer',
            new_name='booked_by',
        ),
        migrations.RenameField(
            model_name='hostelroombooking',
            old_name='room_no_of_filer',
            new_name='booked_by_room_no',
        ),
        migrations.RenameField(
            model_name='hostelroombooking',
            old_name='filer',
            new_name='complainant',
        ),
    ]
