# Generated by Django 3.2.8 on 2022-02-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0005_auto_20220203_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='is_living_in_campus',
            field=models.BooleanField(default=True),
        ),
    ]
