# Generated by Django 3.2.8 on 2022-02-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0006_resident_is_living_in_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='fee_type',
            field=models.CharField(choices=[('liv', 'LIVING'), ('nlv', 'NOT LIVING'), ('nd', 'NON DINING')], default='liv', max_length=10),
        ),
    ]
