# Generated by Django 3.2.8 on 2022-02-22 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_RESIDENCE_MODEL),
        ('bhawan_app', '0007_resident_fee_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='hostel',
        ),
        migrations.AddField(
            model_name='facility',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_RESIDENCE_MODEL),
        ),
    ]
