# Generated by Django 3.2.8 on 2022-03-12 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0007_resident_fee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_item', to='bhawan_app.complaint')),
                ('default_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_name', to='bhawan_app.defaultitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='items',
            field=models.ManyToManyField(through='bhawan_app.Item', to='bhawan_app.DefaultItem'),
        ),
    ]
