# Generated by Django 2.2.6 on 2020-02-14 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_PERSON_MODEL),
<<<<<<< HEAD:migrations/0009_visitor.py
        ('bhawan_app', '0008_event'),
=======
        ("bhawan_app", "0007_facility"),
>>>>>>> Linting changes.:migrations/0008_relative.py
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD:migrations/0009_visitor.py
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistor', to='bhawan_app.RoomBooking')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_PERSON_MODEL)),
=======
            name="Relative",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("relation", models.CharField(max_length=50)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bhawan_app.RoomBooking",
                    ),
                ),
>>>>>>> Linting changes.:migrations/0008_relative.py
            ],
            options={"abstract": False,},
        ),
    ]
