# Generated by Django 3.2.8 on 2022-03-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0008_auto_20220313_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultitem',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bhawan_app.complaint'),
        ),
    ]
