# Generated by Django 2.2.6 on 2020-04-02 18:52

import bhawan_app.models.custom_field.multi_select
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0009_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timing',
            name='day',
            field=bhawan_app.models.custom_field.multi_select.MultiSelectField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday'), ('mon,tue,wed,thu,fri,sat,sun', 'Daily'), ('mon,tue,wed,thu,fri', 'Weekday'), ('sat,sun', 'Weekend')], max_length=50),
        ),
    ]
