# Generated by Django 2.2.3 on 2020-03-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0009_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roombooking',
            name='forwarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='relative',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative', to='bhawan_app.RoomBooking'),
        ),
    ]
