# Generated by Django 2.2.3 on 2020-04-05 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_RESIDENCE_MODEL),
        ('bhawan_app', '0010_auto_20200405_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='complainttimeslot',
            name='hostel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_RESIDENCE_MODEL),
            preserve_default=False,
        ),
    ]
