# Generated by Django 2.2.6 on 2020-04-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0010_auto_20200403_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='available_till',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='room_no',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='hostel',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='booked_by_room_no',
        ),
        migrations.RemoveField(
            model_name='roombooking',
            name='hostel',
        ),
    ]
