# Generated by Django 3.2 on 2022-06-02 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_RESIDENCE_MODEL),
        ('bhawan_app', '0011_auto_20220410_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('residing_in_single', models.PositiveIntegerField(default=0)),
                ('residing_in_double', models.PositiveIntegerField(default=0)),
                ('residing_in_triple', models.PositiveIntegerField(default=0)),
                ('total_need_accommodation', models.PositiveIntegerField(default=0)),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_RESIDENCE_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('room_type', models.CharField(choices=[('tot', 'Total Constructed Rooms'), ('gue', 'Guest Rooms'), ('off', 'Official Rooms'), ('dam', 'Damp Rooms')], default='tot', max_length=15)),
                ('occupancy', models.CharField(choices=[('sgl', 'Single'), ('dbl', 'Double'), ('tri', 'Triple')], default='sgl', max_length=15)),
                ('count', models.PositiveIntegerField(default=0)),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.KERNEL_RESIDENCE_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
