# Generated by Django 2.2.3 on 2020-04-13 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0011_complaint_unsuccessful_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='unsuccessful_attempts',
        ),
        migrations.AddField(
            model_name='complaint',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
