# Generated by Django 2.2.6 on 2020-04-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0011_auto_20200404_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintTimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('complaint_type', models.CharField(choices=[('ele', 'Electric'), ('toi', 'Toilet'), ('car', 'Carpentry'), ('cle', 'Cleaning'), ('oth', 'Other')], default='oth', max_length=10)),
                ('timing', models.ManyToManyField(to='bhawan_app.Timing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
