# Generated by Django 2.2.3 on 2020-04-25 13:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_RESIDENCE_MODEL),
        ('bhawan_app', '0012_auto_20200414_0121'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='complainttimeslot',
            unique_together={('complaint_type', 'hostel')},
        ),
    ]
