# Generated by Django 3.2 on 2022-06-04 20:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0013_alter_room_occupancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
