# Generated by Django 2.2.3 on 2020-04-28 12:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_RESIDENCE_MODEL),
        ('bhawan_app', '0013_auto_20200425_1857'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hosteladmin',
            unique_together={('hostel', 'designation')},
        ),
    ]
