# Generated by Django 3.2 on 2022-11-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0015_studentaccommodation_is_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='designation',
            field=models.CharField(choices=[('aw', 'Assistant warden'), ('aw2', 'Assistant warden 2'), ('aw3', 'Assistant warden 3'), ('cw', 'Chief warden'), ('msw', 'Mess Warden'), ('sup', 'Supervisor'), ('war', 'Warden'), ('waw', 'Warden wellness'), ('bscy', 'Bhawan secretary'), ('cscy', 'Cultural secretary'), ('mscy', 'Maintenance secretary'), ('mescy', 'Mess secretary'), ('sscy', 'Sports secretary'), ('tscy', 'Technical secretary'), ('wscy', 'Wellness secretary'), ('dosw', 'DEAN of students welfare'), ('gsha', 'GENSEC Hostel Afairs')], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='hosteladmin',
            name='designation',
            field=models.CharField(choices=[('aw', 'Assistant warden'), ('aw2', 'Assistant warden 2'), ('aw3', 'Assistant warden 3'), ('cw', 'Chief warden'), ('msw', 'Mess Warden'), ('sup', 'Supervisor'), ('war', 'Warden'), ('waw', 'Warden wellness'), ('bscy', 'Bhawan secretary'), ('cscy', 'Cultural secretary'), ('mscy', 'Maintenance secretary'), ('mescy', 'Mess secretary'), ('sscy', 'Sports secretary'), ('tscy', 'Technical secretary'), ('wscy', 'Wellness secretary'), ('dosw', 'DEAN of students welfare'), ('gsha', 'GENSEC Hostel Afairs')], max_length=5),
        ),
    ]
