# Generated by Django 2.2.3 on 2020-10-20 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.KERNEL_RESIDENCE_MODEL),
        ('bhawan_app', '0015_auto_20201020_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='hostel',
        ),
        migrations.AddField(
            model_name='facility',
            name='hostel',
            field=models.ManyToManyField(to=settings.KERNEL_RESIDENCE_MODEL),
        ),
    ]
