# Generated by Django 2.2.3 on 2020-10-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0016_auto_20201020_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='facility_type',
            field=models.CharField(choices=[('mes', 'Mess'), ('spo', 'Sports'), ('can', 'Canteen'), ('lau', 'Laundry'), ('oth', 'Other')], default='oth', max_length=10),
        ),
    ]
