# Generated by Django 4.1.5 on 2024-08-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0017_resident_address_bhawan_resident_registration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='address_bhawan',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
