# Generated by Django 4.1.5 on 2024-12-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0018_alter_resident_address_bhawan'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='admission_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='contact_number_as_bhawan',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
