# Generated by Django 4.1.5 on 2024-12-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bhawan_app', '0019_resident_admission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='registration_date',
        ),
    ]
