from bhawan_app.models.hostel_profile import HostelProfile
from bhawan_app.models.hostel_contact import HostelContact
from bhawan_app.models.hostel_facility import HostelFacility
from bhawan_app.models.hostel_visitor import HostelVisitor
from bhawan_app.models.hostel_room_booking import HostelRoomBooking
from bhawan_app.models.hostel_complaint import HostelComplaint
